### ISSUE TITLE
Wildcard forward?

### ISSUE THREAD

**Issue by nelfer** [zixia/docker-simple-mail-forwarder#13]
Hi,
My current DNS provider has a feature that they can forward `*@mydomain.com` to an email.
Is this possible with your program?
The reason why I need this is because I might give email addresses on the fly. For example, if I'm filing up a survey, I'll put something like `<myname>.<surveycompany>@mydomain.com` and sure enough, I'll get emails. If they spam me, then I block that email (my incoming email) and avoid any future reselling of that address.

Please let me know if this is possible, as I'm looking for a Docker solution to host my own forwarding.

Thanks!

P.S. Didn't know where else to ask this question, so I created it as an issue

**Comment by zixia** [comment]
base on my knowledge, i believe this feature can be implement without problem, because the smf use postfix, which is very powerful for doing anything with email.

but i have no time to check the doc yet, so it will be nice to post the doc here, or send a pull request is more welcome. :)

the format should be '*@domain.com', then smf will accept any username for the domaim, and then forward them as well.

**Comment by nelfer** [comment]
Guess what? Your image already supports this!
Since you mention postfix, I went ahead and investigated how to do wildcard forward. Turns out that if you put simply `@domain.com` it automatically forwards all emails for `@domain.com` to the the specified address.
I tried it, and I saw that the program didn't reject it. Did a few tests to different addresses, and it works!
Thanks!

P.S. Maybe you could do some more tests so that you can officially support it in the documentation.

**Comment by zixia** [comment]
that's great!

if `@domain.com` is supported by postfix, then I believe the SMF scripts will has no problem with that.

could you send a pull request for the documentation? because you are using this and should know how to describe it more than me.

thanks!

**Comment by nelfer** [comment]
I'm new to working with GitHub...so once I figure out how to make a pull request, I'll make it.
Thanks

**Comment by nelfer** [comment]
OK I think I did it... let me know if everything is ok
Thanks!

**Comment by zixia** [comment]
I think everything is ok, except you forgot to doc this feature: `Wildcard forward` :)

**Comment by nelfer** [comment]
It's in the prior pull request. Documented under basic configuration, just saying "if you want all emails for a domain..."

**Comment by zixia** [comment]
ah! got it.

then I could close this issue.

thank you!
