### ISSUE TITLE
Relayhost config

### ISSUE THREAD

**Issue by Duumke** [zixia/docker-simple-mail-forwarder#18]
Hi,

This is a really nice piece of work.
The only thing I'm missing is to be able to select a relay host.
Is it possible to have this into the system like: export SMF_RELAYHOST='@domain:<ip or name of relayhost>'

That would make this great as I have to use a relay host to make the mail reach the correct mailserver.

Thank you for your time.

Duumke

**Comment by zixia** [comment]
Hi Duumke,

I think if we introduce a new config variable SMF_RELAY is acceptable, because it will not affect other users who is not need it, and a relay host sometimes is a must have.

If you could implement it,  a PR request is welcome. Thanks for the feature suggestion.

**Comment by Duumke** [comment]
Hi Zixia,

I've tried building it myself, but unfortunately I'm not capable enough to make that work.
I have some scripting knowledge, but Docker is still new to me.

I hope you (or someone else) will make it possible in the future, cause I can't get it done.

**Comment by Duumke** [comment]
Hi Zixia,

I've got it working locally, but now I have to figure out how GIT works, so I can do a pull request.
The code is on it's way, just give me some time.

**Comment by zixia** [comment]
Hi @Duumke ,

It's great to hear from you again! 

And congratulations for you getting it done finally. :)

**Comment by Duumke** [comment]
I've made a pull request, initial automated tests seem to have gone fine.
Let me know if this is oke with you.

**Comment by zixia** [comment]
Hi @Duumke , thanks for our PR.

Could you please also add a short description in README, so your new feature can be documented, then other users could use it?

Thanks!

**Comment by zixia** [comment]
@Duumke Thanks for your work & contribution!

**Comment by zixia** [comment]
The docker image with `:latest` tag is ready for use, with your PR inside. :)
