### ISSUE TITLE
Base image

### ISSUE THREAD

**Issue by SamMousa** [zixia/docker-simple-mail-forwarder#23]
Is the unofficial base image still needed? 

It would be preferable to use the official alpine image as base.
Also, there are packages in alpine that offer s6, so there is no need to download it manually as the current base image does.

Side note: https://github.com/sillelien/base-alpine hasn't been updated in over a year.

**Comment by zixia** [comment]
Is there anyone want to help to upgrade the Dockerfile?

Pull Request is welcome! :)

**Comment by SamMousa** [comment]
I will make a PR

**Comment by zixia** [comment]
Great, Thank you very much!

**Comment by martijnrondeel** [comment]
I made a PR for this here https://github.com/zixia/docker-simple-mail-forwarder/pull/37

**Comment by zixia** [comment]
@martijnrondeel Thank you for the contribution! 

@SamMousa Could you please have a look on the PR, and make sure it's OK?

I'll go to look why CircleCI did not report the test result...

**Comment by zixia** [comment]
@martijnrondeel Thanks for the contribution and sorry for the delay.

I had merged the PR, hope the CI will turn green soon.

**Comment by zixia** [comment]
@martijnrondeel Had you tested your PR? 

It seems that we had some problem with this PR because of #38 

I'll roll back to the old base image, and please let me know the test result if you have time to help.

**Comment by riptidewave93** [comment]
PR at https://github.com/zixia/docker-simple-mail-forwarder/pull/43 should fix this up :)

**Comment by zixia** [comment]
Great, I'll go to have a look.

**Comment by zixia** [comment]
@SamMousa Could you please have a look at the latest code (and the docker image), and close this issue if it works for you?

We had just merged the PR to upgrade the base image from @riptidewave93

**Comment by SamMousa** [comment]
Yeah, seems to work fine!

**Comment by zixia** [comment]
Awesome!
