### ISSUE TITLE
Help, not working, not that simple

### ISSUE THREAD

**Issue by delmicio** [zixia/docker-simple-mail-forwarder#26]
Hello, I'm trying yo make this work and this is what I've done so far.

- Docker 1.12.4 on 16.04

![image](https://cloud.githubusercontent.com/assets/2908209/22799673/755afa64-eee5-11e6-847b-bd940850cf0b.png)

Here is the log that the console is showing:

> DNS : initial work complete
[cont-init.d] dns_init.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Feb  9 19:15:45 fbdeed7e9cc8 syslog.info syslogd started: BusyBox v1.23.2
DNS : Waiting for dnsmasq
DNS : Starting monitoring loop
Feb  9 19:15:45 fbdeed7e9cc8 user.notice root: dnsmasq: started, version 2.72 cachesize 150
Feb  9 19:15:45 fbdeed7e9cc8 local0.info dnsmasq[2371]: started, version 2.72 cachesize 150
Feb  9 19:15:45 fbdeed7e9cc8 user.notice root: dnsmasq: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect
Feb  9 19:15:45 fbdeed7e9cc8 local0.info dnsmasq[2371]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect
Feb  9 19:15:45 fbdeed7e9cc8 user.notice root: dnsmasq: reading /etc/dnsmasq-resolv.conf
Feb  9 19:15:45 fbdeed7e9cc8 local0.info dnsmasq[2371]: reading /etc/dnsmasq-resolv.conf
Feb  9 19:15:45 fbdeed7e9cc8 user.notice root: dnsmasq: using nameserver 8.8.8.8#53
Feb  9 19:15:45 fbdeed7e9cc8 local0.info dnsmasq[2371]: using nameserver 8.8.8.8#53
Feb  9 19:15:45 fbdeed7e9cc8 user.notice root: dnsmasq: using nameserver 8.8.4.4#53
Feb  9 19:15:45 fbdeed7e9cc8 local0.info dnsmasq[2371]: using nameserver 8.8.4.4#53
Feb  9 19:15:45 fbdeed7e9cc8 user.notice root: dnsmasq: read /etc/hosts - 8 addresses
Feb  9 19:15:45 fbdeed7e9cc8 local0.info dnsmasq[2371]: read /etc/hosts - 8 addresses
Feb  9 19:15:45 fbdeed7e9cc8 user.notice root: dnsmasq: read /etc/hosts.links - 0 addresses
Feb  9 19:15:45 fbdeed7e9cc8 local0.info dnsmasq[2371]: read /etc/hosts.links - 0 addresses
postfix/postfix-script: stopping the Postfix mail system
Feb  9 19:15:45 fbdeed7e9cc8 mail.info postfix/postfix-script[2385]: stopping the Postfix mail system
Feb  9 19:15:45 fbdeed7e9cc8 mail.info postfix/master[99]: terminating on signal 15
Feb  9 19:15:45 fbdeed7e9cc8 mail.info postfix/master[2452]: daemon started -- version 3.0.1, configuration /etc/postfix

Should this be working?
`docker run -tde SMF_CONFIG="$SMF_CONFIG" -p 25:25 zixia/simple-mail-forwarder`

**Comment by delmicio** [comment]
closing because IT WORKS! AWESOME!

check here @htko89 #25

**Comment by zixia** [comment]
@delmicio Glad to hear it works for you. 

Cheers!

**Comment by delmicio** [comment]
@zixia I'm new to docker and it could be nice to explain in the docs that in order to leave the process running in the background you need to add `-td` to the `docker run` code.

what do you think?

**Comment by zixia** [comment]
Agree. Could you send a PR of adding an additional note for that?
