### ISSUE TITLE
SYSTEM ERROR

### ISSUE THREAD

**Issue by dradovic** [zixia/docker-simple-mail-forwarder#29]
When I start the SMF, I see the following in the log:

> 2017-04-25 10:04:12 backend smf ok 16 ESMTP AUTH by testi@testo.com/test
> 2017-04-25 10:04:12 backend smf ok 17 ESMTP TLS AUTH by testi@testo.com/test
> 2017-04-25 10:04:12 backend smf >> Test FAILED!
> 2017-04-25 10:04:12 backend smf >> !!!!!!!!!!!!!!!!!!!! SYSTEM ERROR !!!!!!!!!!!!!!!!!!!!

Is there a way to know better was has failed?

**Comment by zixia** [comment]
Could you post the full output log?

**Comment by dradovic** [comment]
Unfortunately, I had to abandon this approach. So I don't have access to the full log anymore.
