### ISSUE TITLE
Hard coded urls

### ISSUE THREAD

**Issue by Leonas** [zixia/docker-simple-mail-forwarder#30]
What does this code do in build.sh?
```bash
RE='[0-9]+\s+IN\s+A\s+([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)'
[[ `drill DockerMailForwarder.Builder.\`hostname\` @wimi.36c33f49.svc.dockerapp.io` =~ $RE ]] && {
    DMF_BUILD_IP="${BASH_REMATCH[1]}"
}
```

**Comment by zixia** [comment]
The purpose for the code snip here is for getting the IP from build machine.

`wimi.36c33f49.svc.dockerapp.io` is a Docker Cloud Service that services for DNS who will return the source IP of the query package itself.

**Comment by Leonas** [comment]
Thanks for the quick response. Do you have the code for that service? I don't want my email related apps messaging untrusted endpoints (especially not somebody's private server).

**Comment by zixia** [comment]
@Leonas Yes, I understood. 

I have the source, but it will be very hard to prove that the Online Service is run on top of the source I showed you.

`drill` is a DNS query tool like `nslookup`, so the SMF is only doing a DNS lookup, the information is your IP address(only).

If you feel confident about your IP information, you can feel free to **comment out those lines.**

SMF should be able to run without any problem after you delete those code.

**Comment by Leonas** [comment]
Thank you for explaining it - no more worries.

**Comment by zixia** [comment]
You are welcome. :)
