### ISSUE TITLE
Tag new release.

### ISSUE THREAD

**Issue by SamMousa** [zixia/docker-simple-mail-forwarder#32]
The latest tag is quite old. We could use a new tagged version!

**Comment by zixia** [comment]
Thanks for noticing me, buddy! 

I just tagged v0.4.3 for release. Docker image will be ready after a while.

<https://github.com/zixia/docker-simple-mail-forwarder/releases/tag/v0.4.3>

**Comment by zixia** [comment]
@SamMousa Hi, I also want to release v1.0 because SMF is ready for use for a long time.

How do you think?

**Comment by SamMousa** [comment]
I agree; I do think you should use semantic versioning.

So after 1.0 you cannot make incompatible changes without going to 2.0.
http://semver.org/spec/v2.0.0.html

Great work!

**Comment by zixia** [comment]
Glad to hear that you agree we should going to 1.0.

And yes we must follow the semantic versioning.

Cheers!
