### ISSUE TITLE
Exec /init: No such file or directory

### ISSUE THREAD

**Issue by chrismcna** [zixia/docker-simple-mail-forwarder#38]
Hi,

Im struggling to get the docker image to run, container stops shortly after start with finally message

>> Init System for Servicing...
/entrypoint.sh: line 310: /init: No such file or directory

**Comment by chrismcna** [comment]
full log:
>> Chdir to /app...
 ____  _                 _         __  __       _ _
/ ___|(_)_ __ ___  _ __ | | ___   |  \/  | __ _(_) |
\___ \| | '_ ` _ \| '_ \| |/ _ \  | |\/| |/ _` | | |
 ___) | | | | | | | |_) | |  __/  | |  | | (_| | | |
|____/|_|_| |_| |_| .__/|_|\___|  |_|  |_|\__,_|_|_|
                  |_|
  _____                                _
 |  ___|__  _ ____      ____ _ _ __ __| | ___ _ __
 | |_ / _ \| '__\ \ /\ / / _` | '__/ _` |/ _ \ '__|
 |  _| (_) | |   \ V  V / (_| | | | (_| |  __/ |
 |_|  \___/|_|    \_/\_/ \__,_|_|  \__,_|\___|_|


Source#cf113b1 Sun Jul 22 09:47:18 2018 +0000 * master
Built on Sun Jul 22 09:47:53 UTC 2018 by 24c4ddc4ba7e

>> ENV SMF_DOMAIN not set.
>> ENV SMF_CONFIG found. value:[support@******.co.uk:chris.mcna@gmail.com:dfhfdhe456346hgfdhfgh]
>> ARGV arguments found. value:[start]
>> SMF_CONFIG found in ENV. use this settings for forward maps.
>> Setting password[dfhfdhe456346hgfdhfgh] for user support@@******..co.uk ...
Error: could not find any address for the name: `wimi.36c33f49.svc.dockerapp.io'
>> Set hostname to @******.co.uk
>> Start self-testing...
1..17
ok 1 SMF_CONFIG exist
ok 2 SMF_DOMAIN exist
ok 3 virtual maping source is set
ok 4 virtual maping data is set
ok 5 virtual maping db is set
ok 6 system hostname FQDN resolvable
ok 7 postfix myhostname FQDN & resolvable
ok 8 check other hostname setting
ok 9 confirm postfix is running
ok 10 confirm port 25 is open
ok 11 # skip (skip this for 0.3.0 -> 0.4.0) crond is running
ok 12 ESMTP STATTLS supported
ok 13 ESMTP AUTH supported
ok 14 ESMTP STARTTLS connect ok
ok 15 create user testi@testo.com by password test
ok 16 ESMTP AUTH by testi@testo.com/test
ok 17 ESMTP TLS AUTH by testi@testo.com/test
>> Test PASSED


>> CONGRATULATIONS! System is UP and You are SET!
>> Powered by SMF - a Simple Mail Forwarder
>> View in DockerHub: https://hub.docker.com/r/zixia/simple-mail-forwarder


>> Init System for Servicing...
/entrypoint.sh: line 310: /init: No such file or directory

**Comment by chrismcna** [comment]
changed my image from zixia/simple-mail-forwarder to zixia/simple-mail-forwarder:1.0.0 and seem to be having more success

**Comment by chrismcna** [comment]
got a different problem now,
the containers runs but I attempted a telnet test but Connection closed by foreign host.

```
telnet 127.0.0.1 25
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Connection closed by foreign host.
```

Container log
```
>> Init System for Servicing...
[fix-attrs.d] applying owners & permissions fixes...
[fix-attrs.d] 00-runscripts: applying...
[fix-attrs.d] 00-runscripts: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] dns_init.sh: executing...
DNS : Initial Setup
DNS STEP 1 : Creating the dnsmasq-resolv.conf
DNS : Contents of dnsmasq-resolv.conf
-------------------
### Hetzner Online GmbH installimage
# nameserver config
nameserver 213.133.100.100
nameserver 213.133.98.98
nameserver 213.133.99.99


DNS STEP 2 : Adding the linked services
DNS : Initial /etc/hosts calculated
-------------------
#Auto Generated - DO NOT CHANGE
127.0.0.1       localhost
172.17.0.4      7a126bce266f
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters


DNS : initial work complete
[cont-init.d] dns_init.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Jul 24 14:27:57 7a126bce266f syslog.info syslogd started: BusyBox v1.23.2
DNS : Waiting for dnsmasq
DNS : Starting monitoring loop
Jul 24 14:27:57 7a126bce266f mail.crit postfix/postsuper[263]: fatal: scan_dir_push: open directory defer: Permission denied
Jul 24 14:27:58 7a126bce266f local0.info dnsmasq[212]: started, version 2.72 cachesize 150
Jul 24 14:27:58 7a126bce266f user.notice root: dnsmasq: started, version 2.72 cachesize 150
Jul 24 14:27:58 7a126bce266f local0.info dnsmasq[212]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect
Jul 24 14:27:58 7a126bce266f user.notice root: dnsmasq: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect
Jul 24 14:27:58 7a126bce266f local0.info dnsmasq[212]: reading /etc/dnsmasq-resolv.conf
Jul 24 14:27:58 7a126bce266f user.notice root: dnsmasq: reading /etc/dnsmasq-resolv.conf
Jul 24 14:27:58 7a126bce266f local0.info dnsmasq[212]: using nameserver 213.133.100.100#53
Jul 24 14:27:58 7a126bce266f user.notice root: dnsmasq: using nameserver 213.133.100.100#53
Jul 24 14:27:58 7a126bce266f local0.info dnsmasq[212]: using nameserver 213.133.98.98#53
Jul 24 14:27:58 7a126bce266f user.notice root: dnsmasq: using nameserver 213.133.98.98#53
Jul 24 14:27:58 7a126bce266f local0.info dnsmasq[212]: using nameserver 213.133.99.99#53
Jul 24 14:27:58 7a126bce266f user.notice root: dnsmasq: using nameserver 213.133.99.99#53
Jul 24 14:27:58 7a126bce266f local0.info dnsmasq[212]: read /etc/hosts - 7 addresses
Jul 24 14:27:58 7a126bce266f user.notice root: dnsmasq: read /etc/hosts - 7 addresses
Jul 24 14:27:58 7a126bce266f local0.info dnsmasq[212]: read /etc/hosts.links - 0 addresses
Jul 24 14:27:58 7a126bce266f user.notice root: dnsmasq: read /etc/hosts.links - 0 addresses
Jul 24 14:27:58 7a126bce266f mail.crit postfix/postsuper[309]: fatal: scan_dir_push: open directory defer: Permission denied
Jul 24 14:28:00 7a126bce266f mail.crit postfix/postsuper[355]: fatal: scan_dir_push: open directory defer: Permission denied
Jul 24 14:28:01 7a126bce266f mail.crit postfix/postsuper[401]: fatal: scan_dir_push: open directory defer: Permission denied
Jul 24 14:28:02 7a126bce266f mail.crit postfix/postsuper[447]: fatal: scan_dir_push: open directory defer: Permission denied
Jul 24 14:28:03 7a126bce266f mail.crit postfix/postsuper[493]: fatal: scan_dir_push: open directory defer: Permission denied
Jul 24 14:28:04 7a126bce266f mail.crit postfix/postsuper[539]: fatal: scan_dir_push: open directory defer: Permission denied
Jul 24 14:28:05 7a126bce266f mail.crit postfix/postsuper[585]: fatal: scan_dir_push: open directory defer: Permission denied
Jul 24 14:28:07 7a126bce266f mail.crit postfix/postsuper[631]: fatal: scan_dir_push: open directory defer: Permission denied

```

**Comment by zixia** [comment]
Can you run `zixia/simple-mail-forwarder:1.0.0` without docker compose?

That version should be ok because it had been used for over 12 months and without any issue report.

**Comment by chrismcna** [comment]
much better, telnet is responding, will give it a proper test and let you know

**Comment by zixia** [comment]
Good luck!

**Comment by chrismcna** [comment]
Amazing guys, working as expected when not using docker-compose

**Comment by zixia** [comment]
Glad to hear that, cheers!
