### ISSUE TITLE
Multiple domain names?

### ISSUE THREAD

**Issue by LBognanni** [zixia/docker-simple-mail-forwarder#45]
Hi, I didn't find any mention in the docs about having multiple domain names.
Is this supported in any way?
I tried it and it looks like it is only forwarding emails from the first domain.
Emails sent to the second domain fail with:

    NOQUEUE: reject: RCPT from mail-vs1-f42.google.com[209.85.217.42]: 454 4.7.1 <address@seconddomain.com>: Relay access denied;
    disconnect from mail-vs1-f42.google.com[209.85.217.42] ehlo=2 starttls=1 mail=1 rcpt=0/1 data=0/1 quit=1 commands=5/7

**Comment by zixia** [comment]
Yes, it should support multiple domain names, it's by design.

If you still have issue about this please have a look into the code, because I had forgot the details... ;-p

**Comment by LBognanni** [comment]
I had a second look and you are right, it works!
I just didn't reload my smf container properly after changing my `docker-compose.yml`.

For anyone having the same problem, if you are using `docker-compose restart [smf name]` to reload a container, it will **not** read the new configuration; however running `docker-compose up -d` will correctly reload any changes made to the docker-compose.yml file
