### ISSUE TITLE
Tag latest

### ISSUE THREAD

**Issue by kachkaev** [zixia/docker-simple-mail-forwarder#5]
Hi Zhuohuan and thank you for this image – really happy to discover it!
I prefer specifying exact version in my `docker-compose.yml` and it seems that `0.4.0` tag is outdated. Could you please create a new fixed tag for what is now `latest`?

Cheers!

**Comment by zixia** [comment]
Thanks for your like SMF.

Your 0.4.1 tag is on the way... :)

```
Building
0.4.1
a minute ago
```

Please feel free to let me know if there has any other issues.

have a good day!
