### ISSUE TITLE
Building for ARM

### ISSUE THREAD

**Issue by dimitrovs** [zixia/docker-simple-mail-forwarder#9]
I switched the Dockerfile to build from this image: FROM armbuild/alpine and I added the openssl package. It builds fine and appears to start, but it can't find the /init file. Where is this /init file supposed to come from?

**Comment by zixia** [comment]
I'm not sure, but it seems the `/init` should comes with the `sillelien/base-alpine:0.10` image?

please correct me if I'm wrong.

**Comment by dimitrovs** [comment]
Thanks, that was very helpful. All I had to do was port sillelien/base-alpine:0.10 to ARM (stefand/base-alpine-armhf) then I just changed the Dockerfile to build from it and everything works. I created a fork for ARM builds here:
https://github.com/dimitrovs/docker-simple-mail-forwarder-armhf/

Let me know if you prefer to have it as a branch on the main repo. I am not sure if you can build for ARM with Docker on x86, but I noticed that Docker Hub automated builds don't work with the ARM images, so I had to push manually.

**Comment by zixia** [comment]
@dimitrovs thanks man, it's great work! 👍 

I'd love to have it as a branch on the main repo. Would you like to be maintainer of the SMF with me together? because I have no experience on ARM. :)

**Comment by dimitrovs** [comment]
Sure, I don't have much experience with Docker on ARM either, but it looks like it's all the same, as long as the build machine has ARM CPU :)
I created a pull request for the new branch: https://github.com/zixia/docker-simple-mail-forwarder/pulls

We should bring the README file from main and just add a note that this is the ARM branch. I will look into how we can have both ARM and x86 images on Docker Hub, but I don't think it's possible under the same handle. May be we can keep the Docker Hub image here: https://hub.docker.com/r/stefand/simple-mail-forwarder-armhf/ and I will just point it to the armhf branch of https://github.com/zixia/docker-simple-mail-forwarder ?

**Comment by zixia** [comment]
Ok, All looks good. :)

Could you merge the pull request by yourself? Because I had added you as collaorator.

About the image, I think there could be better if we push the image together(i.e. as `simple-mail-forwarder:armhf-semver`),  I had added you to the docker hub collaborator too.

However, it's also ok to me if we had to keep the image seperate, there would no problem for keeping armhf version under your account and link them together. pick your decide please.
